# Generated by Django 4.2 on 2023-04-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation_subscription10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Специальное предложение')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Цена по скидке?')),
            ],
            options={
                'verbose_name': 'Абонемент 10 консультаций',
                'verbose_name_plural': 'Абонемент 10 консультаций',
            },
        ),
        migrations.CreateModel(
            name='Consultation_subscription15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Специальное предложение')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Цена по скидке?')),
            ],
            options={
                'verbose_name': 'Абонемент 15 консультаций',
                'verbose_name_plural': 'Абонемент 15 консультаций',
            },
        ),
        migrations.CreateModel(
            name='Consultation_subscription5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.IntegerField(default=0, verbose_name='Специальное предложение')),
                ('is_discount', models.BooleanField(default=False, verbose_name='Цена по скидке?')),
            ],
            options={
                'verbose_name': 'Абонемент 5 консультаций',
                'verbose_name_plural': 'Абонемент 5 консультаций',
            },
        ),
        migrations.CreateModel(
            name='Family_consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Семейная консультация',
                'verbose_name_plural': 'Семейная консультация',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('subject', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Individual_consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Индивидуальная консультация',
                'verbose_name_plural': 'Индивидуальная консультация',
            },
        ),
    ]
