# Generated by Django 4.2 on 2023-04-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Семейная консультация',
                'verbose_name_plural': 'Семейная консультация',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('subject', models.TextField(max_length=500)),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Индивидуальная консультация',
                'verbose_name_plural': 'Индивидуальная консультация',
            },
        ),
        migrations.CreateModel(
            name='Subscription10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.CharField(default=0, max_length=140, verbose_name='Специальное предложение')),
            ],
            options={
                'verbose_name': 'Абонемент 10 консультаций',
                'verbose_name_plural': 'Абонемент 10 консультаций',
            },
        ),
        migrations.CreateModel(
            name='Subscription15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.CharField(default=0, max_length=140, verbose_name='Специальное предложение')),
            ],
            options={
                'verbose_name': 'Абонемент 15 консультаций',
                'verbose_name_plural': 'Абонемент 15 консультаций',
            },
        ),
        migrations.CreateModel(
            name='Subscription5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=140)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('discount', models.CharField(default=0, max_length=140, verbose_name='Специальное предложение')),
            ],
            options={
                'verbose_name': 'Абонемент 5 консультаций',
                'verbose_name_plural': 'Абонемент 5 консультаций',
            },
        ),
    ]
