# Generated by Django 4.2 on 2023-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
